In [5]:
import numpy as np

data = np.genfromtxt("sales_data.csv",delimiter=',',skip_header=True)

product1_sum = np.sum(data,axis=0)

print(product1_sum)

[190. 210. 202. 217. 226. 225. 248.]


In [8]:
#Find the average daily sales for each product.
average_daily_sales = np.mean(data,axis=0)
print(average_daily_sales)

[38.  42.  40.4 43.4 45.2 45.  49.6]


In [11]:
#Identify the product with the highest total sales.
pdt_max = np.max(data,axis=0)
print(pdt_max)

[80. 78. 85. 88. 90. 87. 92.]


In [16]:
#Find the total sales for all products on Wednesday.
total_sales =   np.sum(data[:,2])
print("total sales on Wednesday = ",total_sales)

total sales on Wednesday =  202.0


In [19]:
#Determine the day with the highest overall sales across all products.
max_day = np.max(data[:,:])
max_day

np.float64(92.0)

In [20]:
days = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']

In [24]:
day_with_highest_sales = np.argmax(np.sum(data,axis=0))
highest_sales_day =days[day_with_highest_sales]
print(highest_sales_day)
print(day_with_highest_sales)

Sunday
6
