In [2]:
import numpy as np 
data = np.genfromtxt("days.csv",delimiter=',',skip_header=1)

In [14]:
#What is the average sales for each product? Which product had the highest average sales?
goods = np.mean(data,axis=0)
goods

#it will give the index as output not the exact value needed
goods_max = np.argmax(goods) 
print(goods_max)

#now following will return exact count
goods_max_count = goods[goods_max]
print("Maximum amount were sold :",goods_max_count)

2
Maximum amount were sold : 290.0


In [12]:
#For each product, which day had the highest sales, and how many units were sold on that day?
day_sum = np.sum(data,axis=0)
print(day_sum)
print("Total sales made on Monday = ",day_sum[0])

[310. 600. 870. 390. 690.]
Total sales made on Monday =  310.0


In [38]:
#Sales made by first oroduct
week_sale = np.sum(data,axis=1)
print("Total sales made by first product = ",week_sale[0])

Total sales made by first product =  1000.0


In [23]:
#For each product, calculate the difference between the highest and lowest sales days. Which product had the highest fluctuation in sales?
pdt_max = np.max(data,axis=1)
print(pdt_max)

pdt_min = np.min(data,axis=1)
print(pdt_min)

fluctuation = pdt_max-pdt_min
fluct_max = np.max(fluctuation)
print(fluct_max)

highest_fluctuation_index = np.argmax(fluctuation)
print(highest_fluctuation_index)
highest_fluctuation_value = fluctuation[highest_fluctuation_index]

print(f"Product {highest_fluctuation_index + 1} had the highest fluctuation of {highest_fluctuation_value:.2f}")

[300. 250. 320.]
[100.  90. 120.]
200.0
0
Product 1 had the highest fluctuation of 200.00


In [30]:
#What is the total sales amount for all products across all days?
total_sales = np.sum(data,axis=0)
print(total_sales)
total = np.sum(total_sales)
print(total)
#Here we find through two steps. We can find through one step easily as follows.

total_sum = np.sum(data)
print("Total sales made = ",total_sum)

[310. 600. 870. 390. 690.]
2860.0
Total sales made =  2860.0


In [39]:
#What percentage of the total weekly sales did each product contribute?
first_pdt_percent = week_sale[0] / total_sum *100
second_pdt_percent = week_sale[1] / total_sum *100
third_pdt_percent = week_sale[2] / total_sum *100

print(first_pdt_percent)
print(second_pdt_percent)
print(third_pdt_percent)

34.96503496503497
28.671328671328673
36.36363636363637
